development:
  adapter: solid_cable

test:
  adapter: test

production:
  adapter: solid_cable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails_refyned_production
